name: SkyWars
main: SkyWars\Main
version: "2.1"
api: [1.0.0]
load: POSTWORLD
author: EnderPE
commands:
 sw:
  permission: SkyWars.command.sw
  description: Main Command
  usage: /sw <set|remove>
 lobby:
  permission: SkyWars.command.lobby
  description: back to lobby
  usage: /lobby
permissions:
 SkyWars.*:
  description: the main permission
  default: op
  children:
   SkyWars.command.*:
    description: use commands in plugin
    default: op
    children:
     FSurvivalGame.command.lobby:
      description: back to lobby
      default: true
     FSurvivalGame.command.fsg:
      description: set SurvivalGame
      default: op
   FSurvivalGame.touch.startgame:
    description: click the sign and join the game
    default: true
